"""add status to resume

Revision ID: 72da6080d299
Revises: 907a1f8f24ea
Create Date: 2026-08-07 15:01:08.245702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72da6080d299'
down_revision: Union[str, Sequence[str], None] = '907a1f8f24ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('status', sa.String(), nullable=True))
    op.add_column('resumes', sa.Column('parser_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parser_confidence')
    op.drop_column('resumes', 'status')
    # ### end Alembic commands ###
